# Generated by Django 2.1.5 on 2019-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_1', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('object_2', models.CharField(max_length=100)),
            ],
        ),
    ]
